[package]
name = "day19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.0"
itertools = "0.12.0"
lazy_static = "1.4.0"
impl_ops = "0.1.1"
rustc-hash = "1.1.0"
